plugins: 
  - jekyll-remote-theme

remote_theme: pages-themes/cayman
title: Feature Selection using Stochastic Gates
description: Python/R library for feature selection in neural nets 


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
